### ISSUE TITLE
when tz offset is in the pattern, the date should be in UTC

### ISSUE THREAD

**Issue by lovelypig5** [nomiddlename/date-format#10]
see test/date_format-test.js
dateFormat.asString(dateFormat.ISO8601_WITH_TZ_OFFSET_FORMAT, tzDate)
            .should.eql('2010-01-11T14:31:30.005+1100');
            .should.eql('2010-01-11T03:31:30.005+1100');

should .should.eql('2010-01-11T03:31:30.005+1100'); be 
            .should.eql('2010-01-11T03:31:30.005+0000');

**Comment by nomiddlename** [comment]
[ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) says that it should be local time if you're displaying the offset. So, you are correct the test is wrong - but in a different way to how you're suggesting. This should be fixed when #14 is fixed.

Not sure why it's taken me 6 months to reply to this issue though. Sorry about that.

**Comment by nomiddlename** [comment]
Closing this one, now that #14 has been fixed.
