### ISSUE TITLE
Consider adding string representations of months

### ISSUE THREAD

**Issue by safazi** [nomiddlename/date-format#15]
Consider adding MMM or MMMM that would output as Oct or October respectively.

**Comment by nomiddlename** [comment]
Hi, thanks for the suggestion but I think that's probably beyond the scope of this little library. I don't want to have to deal with internationalisation. If you're looking to do something like this then either take a look at [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat) or [momentjs](https://momentjs.com).
