### ISSUE TITLE
Critical issue with dataformat 

### ISSUE THREAD

**Issue by gauravbrills** [nomiddlename/date-format#19]
console.log(dateFormat("ddmmyyyy", dateFormat.parse('yyyy-mm-dd', '2019-10-31'))) 

this is giving output as **01102019**.

**This seems to be an issue with all dates ending with 31 .**

this should be fixed urgently !!!!

**Comment by nomiddlename** [comment]
The pattern for month is `MM`. If I use the following code, with the latest date-format, I get the correct result:
```javascript
format("ddMMyyyy", format.parse('yyyy-MM-dd','2019-10-31'))
'31102019'
```

**Comment by gauravbrills** [comment]
ahh ok ; so basically https://www.w3.org/QA/Tips/iso-date iso formats like moment right .
