### ISSUE TITLE
The 'L' millisecond flag can return 3 digits

### ISSUE THREAD

**Issue by traubad** [nomiddlename/date-format#21]
While it generally works correctly, it looks like in certain edge cases, the 'L' flag can return 3 digits instead of 2.
format: "mm/dd/yyyy HH:MM:ss.L"
output: 03/16/2020 19:50:22.100 #

**Comment by nomiddlename** [comment]
There is no 'L' flag in this library. Are you sure you have the correct project?

**Comment by traubad** [comment]
Well this is embarrassing, I was using the dateformat library and posted a bug in the date-format library.  My bad!
