### ISSUE TITLE
format parse adds a month in the default format

### ISSUE THREAD

**Issue by achalkias** [nomiddlename/date-format#23]
Greetings,
My string date is 

> 1995-09-09T23:16:56.161

And when i parse it to the 

> ISO8601_FORMAT

 it returns it with a month added like this

> Mon Oct 09 1995 23:16:56 GMT+0200 (Eastern European Standard Time)

This is my code. Thanks in advance.

    console.log(state.date); //1995-09-09T23:16:56.161

    const formatedDate = format.parse(format.ISO8601_FORMAT,state.date);

    console.log(formatedDate); //Mon Oct 09 1995 23:16:56 GMT+0200 (Eastern European Standard Time)

    const birthDate = format('dd/MM/yyyy',formatedDate);

    console.log(birthDate); //09/10/1995

**Comment by peteriman** [comment]
Hi @achalkias, I'm unable to get your results using `date-format@2.1.0` and `date-format@3.0.0`.

```javascript
const format = require('date-format');

const state = { date: "1995-09-09T23:16:56.161" };
console.log(state.date);
// 1995-09-09T23:16:56.161

const formatedDate = format.parse(format.ISO8601_FORMAT,state.date);
console.log(formatedDate);
// 1995-09-09T21:16:56.161Z

const birthDate = format('dd/MM/yyyy',formatedDate);
console.log(birthDate);
// 09/09/1995
```
