### ISSUE TITLE
Colon in timezone

### ISSUE THREAD

**Issue by thernstig** [nomiddlename/date-format#24]
According to https://en.wikipedia.org/wiki/ISO_8601 the timezone is recommended to contain a colon.

> Representations can be done in one of two formats – a basic format with a minimal number of separators or an extended format with separators added to enhance human readability.[14][15] The standard notes that "The basic format should be avoided in plain text."[16] The separator used between date values (year, month, week, and day) is the hyphen, while the colon is used as the separator between time values (hours, minutes, and seconds). For example, the 6th day of the 1st month of the year 2009 may be written as "2009-01-06" in the extended format or simply as "20090106" in the basic format without ambiguity.

RFC3339, that is a profile of ISO 8601, also states that the offset between local time and UTC is defined as:

> time-numoffset  = ("+" / "-") time-hour ":" time-minute

As such, should the the O format string should most likely include a colon, right?

**Comment by peteriman** [comment]
I believe this is what @thernstig is saying:
`2022-01-06T08:47:48.003+0800` -> `2022-01-06T08:47:48.003+08:00`

https://github.com/nomiddlename/date-format/blob/28083658c88ed5708c5019a88ad533228fb6d929/lib/index.js#L30

```diff
- return timezoneOffset < 0 ? "+" + h + m : "-" + h + m; 
+ return (timezoneOffset < 0 ? "+" : "-") + h + ":" + m; 
```

Might also want to include a case of `+0000` or `+00:00` to return `Z` instead.

**Comment by thernstig** [comment]
@peteriman thank you for that comment. I re-read my original post and must have been very tired when writing it, as it ended quite abruptly without better examples of what I meant, and where the change should be made.

**Comment by peteriman** [comment]
For more details: https://github.com/nomiddlename/date-format/pull/27#issue-1095354995
